### ISSUE TITLE
Proposal for eventregistration (adding icons)

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#10]
adding icons (see  image)
![signattend](https://user-images.githubusercontent.com/2960236/47433817-76583980-d7a1-11e8-87e1-9a9a9450df80.png)

**Comment by Egnarts94** [comment]
I like these Icons, I will add them in the next update.

From where did you get this form?
I don't know something about "optional comment"

**Comment by jojo12** [comment]
??? What do you mean? This form is official inside JEM Frontend since 2.2.1!

**Comment by Egnarts94** [comment]
Also the commentary field? o.O
How can I activate that? Didn't find an option.

**Comment by jojo12** [comment]
JEM Settings >User Control > Registrations >Allow Comments = YES

**Comment by Egnarts94** [comment]
Ooooh, I didn't know about that, I think there will be something to do for JEM-Responsive :D

**Comment by jojo12** [comment]
There is more inside than you think! ;-)

**Comment by Egnarts94** [comment]
I did a rework in the override. But now after the integration the old form is used. I am investigating....

**Comment by Egnarts94** [comment]
It's fixed. A new build is available in the pull-request.
