### ISSUE TITLE
integration of override: visibility of attending statues in FR

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#11]
Perhaps you don't know this: There is a possibility to show who's attending/not attending in FE. (until now in template override) but with prepares in the JEM core.
In the JEM settings you can choose who can see this in FE:
JEM settings>Event page>Registration>Show attendee names to....
Because of the possibility of this choice, I propose to integrate it in the JEM core.
It shows the attending status too with icons.
I have the needed files for that!
![attendlist](https://user-images.githubusercontent.com/2960236/47634776-f7715100-db52-11e8-8702-8958b48d8512.png)

**Comment by jojo12** [comment]
Meanwhile there's a new post in the forum just asking for that!
(Hoffis solution is with numbers 1/1  -1 1?)

**Comment by Egnarts94** [comment]
I added a setting to Jem settings>Event page>Registration>Show not only attending users
A updated Build is available at the pull-request (https://github.com/jemproject/JEM-Project/files/2526271/pkg_jem_v2.3.0-dev1.9.zip)

The icons are only available in the responsive version of JEM. I did *no* change on the old layout.

**Comment by jojo12** [comment]
I am not so happy with the default_attendings_responsive.php. In Hoffis part there are just preparations to make visible attendings/nonattenings/invited and waitinglists. . This has consequences too for the cb_jem_plugins!

**Comment by Egnarts94** [comment]
Ehm, I think I did the same?
With the new Build (v2.3.0-dev1.9.zip), there is a Backend-option to switch between the default listing (only attending users) and all users (attentding, waitinglist, invited, nonattending) in the event view.
This is just a more powerful integration of the solution postet by you in the forum (https://www.joomlaeventmanager.net/forum/jem-2-2-x-on-joomla-3/10077-see-both-attending-and-unattending-registrations#23528).
Normally there should not be any problems in combination with CB. 
Do you have CB? 
Where are the problems? 
What are the things you are "not so happy with the default_attendings_responsive.php"?

**Comment by jojo12** [comment]
I have to test more, I will write more. I am away from home. First waiting for Joomla! 3.9. today!
