### ISSUE TITLE
dev1.10: undefined property

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#12]
afater a fresh install of pkg_jem_v2.3.0-dev1.10 I got a lot of: e.g.
Notice: Undefined property: stdClass::$layoutstyle in mysite.ch/httpdocs/components/com_jem/helpers/helper.php on line 1240

and
Notice: Undefined property: stdClass::$useiconfont in mysite.ch/httpdocs/components/com_jem/helpers/helper.php on line 1252

EDIT:
this happens when no modern responsive style!

**Comment by jojo12** [comment]
strange: after some more trials, I don't get this anymore. (Perhaps some cache things?)

**Comment by Egnarts94** [comment]
This happens if no value is in the database.
Do you know how to write a default value into the database on during installation of JEM? I didn't find out until yet.

Edit: I found it. Fixed with the next build
