### ISSUE TITLE
Proposal for other attending status icons and colours

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#14]
![attendlist](https://user-images.githubusercontent.com/2960236/47796881-803fe680-dd25-11e8-952c-3e5bf98b5872.png)
I propose:
green fa-check-square for attending
red fa-times-circle for non attending
blue fa-question-circle for invited
orange fa-exclamation-circle for waitinglist  (exclamation you have to do something)

and I find it is better to have at first the icon and then the name! It's more in a column

the tooltip is very good!

**Comment by jojo12** [comment]
and the new sorting of attendings is exciting! Bravo!

**Comment by Egnarts94** [comment]
I also do a compromise:
* All attendee-status-icons are circles
* replace the list icon with fa-exclamation-circle
* the icons are before the name in the next build I will upload
