### ISSUE TITLE
proposal for responsive: class for avatar icon

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#18]
For me the avatar img in the attending list (with cb) is too big. In the old non responsive part the img had an extra class. So it was very easy to add in css a max-width.  (I prefer an img of 20 px here)

**Comment by jojo12** [comment]
sorry, this is too much individual. And I can change it by myself.

**Comment by Egnarts94** [comment]
Sorry for my late reaction.
I don't know how it looks with cb avatars. I think there could be something to do for me.
Could you share me an url where JEM-Responsive and CB are activated?

**Comment by Egnarts94** [comment]
I added a width of 30px so that I can see whats in the profile picture, with 20px it was very small to see whats on the picture.
It's okay?

**Comment by jojo12** [comment]
Yes, if it looks good in the column

**Comment by jojo12** [comment]
I tested and it looks very good! And if someone wants it smaller, he can manipulate it without changing other images too. Thanks.
