### ISSUE TITLE
 dev1.2: fontawesome seems not ready 

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#2]
I installed on an new joomla. when I activate the font icons, they are not there. (But I have to say, I am testing on a 3.9.RC)

Sorry, I tested on a protostar template, there is no fontawesome.
When I test e.g. on ja_simply, all is ok

Egnarts94 answer:
No, you were correct. I forgot to create the folder in media/com_jem for FontAwesome...
Will be fixed with the next build

**Comment by jojo12** [comment]
I added manually the line in jem.xml and
I added the missing folder (Fontawesome) in media and 
tried again in protostar -> icons are here in protostar too! ok!

**Comment by Egnarts94** [comment]
Fixed in https://github.com/Egnarts94/JEM-Project/commit/0730f3f8c87a04f7f079247b5ce8f8d6606e0d5c and new version is uploaded to the pullrequest.
