### ISSUE TITLE
Bug in responsive venue: there's no map; in legacy venue, there's the map

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#21]
Really strange.
when I look in live css, in legacy I see a relation to the googlemap.css. In responsive not.
Can this be because of that?

**Comment by jojo12** [comment]
I took 
`.map_canvas {
    height: 250px;
    margin: 10px 0px 10px 0px;
    border: 1px solid grey;
}`
from googlemap.css and inserted it for testing in jem-responsive.css
and....
SUCCESS: the map is there!
so there must be a broken relation between!

**Comment by jojo12** [comment]
is it possible, that class "map_canvas" can be defined outside of JEM and interferes with the map of JEM?

**Comment by jojo12** [comment]
sorry- It seems to be an interference problem with ja_purity_iii template, with protostar there's  no problem.

**Comment by Egnarts94** [comment]
Ehm, please try the following:
Go to <JoomlaRoot>->media->com_jem->css and duplicate all files that do not have a "...-responsive.css" in their name and change the name of the duplicated files to this schemata.
Example:
There is a file called "googlemap.css"
After that there are two files:
googlemap.css
googlemap-responsive.css

**Comment by jojo12** [comment]
Sorry, for the late response. I first tried something other. And I didn't have enough time to test.
Now I tested: Your proposal works well on all of my templates! Thanks

**Comment by jojo12** [comment]
I had now a case, I had to add for map-canvas
width: 100%;
if not, there was only a line on the right side of the venue in event details!

**Comment by jojo12** [comment]
I come back to this problem: Because the problem is not yet away, I tested more:
It's the "#jem .jem-row {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: space-between;
}
or inside the flex, which is causing this problem!
We need this what for? Can I disable this?

**Comment by Egnarts94** [comment]
The CSS code you posted creates the horizontal order of nearly all items.
For example it is uses in the simplelist (table view) for each line, or in the simplelist (modern view) for each event details like category, date/time, city, location etc.

I think it's time that I look for an api-key to fix that.

**Comment by jojo12** [comment]
I am testing with the new JEM v2.3.0-dev.0.4.6:
now I found this:
the map problem is only, when you use the last possibility: google with the key.
when you use google map, then the map is on a good position.
![map with apikeymap](https://user-images.githubusercontent.com/2960236/57197291-d8220900-6f65-11e9-9880-dbb37c8aee8a.png)

**Comment by Egnarts94** [comment]
Hey, until now I never used any map in JEM.
Can you say me what I need to do to get a working map to be displayed, like you mentioned?
What and where I have to insert in the Venue itself, what settings I have to do?

**Comment by jojo12** [comment]
ok, I'll try:
got JEM>settings>Eventpage>Venues>choose map service:  you have 4 options
no mapservice
display link to google maps
display google map
display google map (api-key) you need an api-key, if you choose this you need to insert in additional fields com and de (for german)
you can do the same on JEM>settings>Global Parameters>Venues>Choose map service: 

if you have an api-key, you insert it in JEM>settings>Global Parameters>Google Api-key:

you save and look for the result:
no map service: --> nothing
link to google map -->an icon which opens a new page with google maps
display google map -->I think this is an iframe with google map
display google map (api-key) -->It looks near the same like the iframe but is otherwise and you can't open the map.

the problem is only the google map with api-key in the event window (see my screenshot above.

sometimes this map work even without api-key, then you can try yourself. If it doesn't work, you need to create an api-key or you look into my site intra.folk-tanz.ch/anlaesse 
EDIT: 
on JEM>settings>Global Parameters>Venues>Display venue address must be set to yes

**Comment by jojo12** [comment]
I think, I have it
the end `</div>` from `<div class="jem-row jem-wrap-reverse">`    
must be earlier, before the
`<?php if ($params->get('event_show_mapserv') == 3) : `?>`

**Comment by Egnarts94** [comment]
Ahh I found my problem. In the venue I need to check the Geodata->Add a map link

**Comment by Egnarts94** [comment]
@jojo12 I should be fixed now.
Please test it.

**Comment by jojo12** [comment]
@Egnarts94: It fixed very well! Thanks
