### ISSUE TITLE
Calendar Component with Calendar Module

### ISSUE THREAD

**Issue by depebo** [Egnarts94/JEM-Project#24]
Build from develop-egnarts branch, installed on clean 3.9.5, installed demo data
Published calendar module in position-7 (right)
Added menu item - JEM Calendar
Loaded page showing Calendar component and Calendar module
Reduced browser window width till right bar goes under component
At this point calendar module takes 100% width and all days appear in one column, just like calendar component, but with missing CSS

**Comment by jojo12** [comment]
This is wanted like that, if not, the calendar is nearby not readable

**Comment by depebo** [comment]
Pretty sure you would not want this. Hold on closing this issue - I will provide screen shot form the test system in a few days (it is on the different laptop)

**Comment by jojo12** [comment]
No, sure, I will not close. Do you have a better solution for mobiles?

**Comment by depebo** [comment]
In this particular instance, IMHO, the calendar _module_ should go wide and take all width available.
If you asking if I have better overall solution for JEM mobile, then no, I don't. Hence my drive for design review and plan before we start version 4 upgrade.

**Comment by Egnarts94** [comment]
It would be good if you give us a screenshot.
As far as I understood, the calendar module has style problems on mobile devices?

**Comment by depebo** [comment]
![image](https://user-images.githubusercontent.com/14943618/56445204-e92b1300-62f3-11e9-8618-0a781fa48cbf.png)
this is what calendar module looks like

**Comment by depebo** [comment]
![image](https://user-images.githubusercontent.com/14943618/56445255-3909da00-62f4-11e9-8615-2b52de49dfee.png)
Pretty sure this was not the intention?

**Comment by depebo** [comment]
![image](https://user-images.githubusercontent.com/14943618/56445287-6f475980-62f4-11e9-9465-3470a7f5ba99.png)
Calendar component looks fine.

**Comment by jojo12** [comment]
@depebo:
You're right: on mobile the mod_jem_cal looks wrongly. The components menu calendar looks ok.

**Comment by Egnarts94** [comment]
I think there is something broken in your css?
Take a look at https://jem-test.lkgchemnitz.de ,my Testpage for development.
![image](https://user-images.githubusercontent.com/14231804/56453246-ef46e100-633f-11e9-906e-6bc7fdd29ce8.png)
It looks correct, tested with small browser on desktop (chrome, firefox) and mobile phone browser (also chrome). 
Edit: Also tested with the device simulation of chrome development tools, same correct result.

Edit2: I found the problem. It occurs when the calendar module is on the same page as the calendar view.
