### ISSUE TITLE
pkg_jem_v2.3.0-dev0.4.6: Bug when attachments enabled 

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#29]
In settings: attachments are enabled, I try to open editvenue:
500 Layout „edit_attachments“ nicht gefunden!

**Comment by jojo12** [comment]
It's  a TYPO: it searches "edit_attachments" and the file is "edit_attachment.php". I renamed the file to edit_attachments.php and then it worked!
EDIT: Addendum:
the same TYPO is in default template too!

**Comment by Egnarts94** [comment]
Thank you, its changed.
