### ISSUE TITLE
JEM2.3dev1: error in JEM-Module_Wide

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#3]
@egnarts: in this new version I get error notices which were not in the previous version:
Notice: Undefined variable: row in mysite.ch/httpdocs/modules/mod_jem_wide/tmpl/default_jem_eventslist.php on line 92

Notice: Undefined variable: row in mysite.ch/httpdocs/modules/mod_jem_wide/tmpl/default_jem_eventslist.php on line 93

Egnarts94 answer:
Yea, thats a copy&paste mistake... I will fix it.

**Comment by Egnarts94** [comment]
Interesting: I fixed it and changed $row to $item but the recurrence icons do not appear... are they available at all in the jem_mod_wide module?

**Comment by jojo12** [comment]
@before the recurrence icons were only in simple list (and event and editevent)
