### ISSUE TITLE
Local Dev Setup

### ISSUE THREAD

**Issue by depebo** [Egnarts94/JEM-Project#34]
@Egnarts94 
As requested in forum post - here is a post of issue:

Clone Egnarts94/JEM-Project
Local copy branch dev23 to dev23-depebo
Make all changes in dev23-depebo branch
Once permitted Push back to remote

How do we keep all branches in sync in this case - by merging all changes between branches manually?
Will it not be better for individuals to fork and work on that fork, periodically syncing the fork with Egnarts94/JEM-Project and letting you to pull changes from forks?

I am still learning Git, please forgive me if this does no make sense.

**Comment by Egnarts94** [comment]
You are right, I just wanted to begin someting to do...
We need to think about how do wie build our branches and merges.
Take a look here: https://de.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
Are you german? Or which language is your native?

Edit: I sent you an invite to this repo.

**Comment by depebo** [comment]
Invite received, will try pushing my branch (dev23-depebo) now.
Russian and English both fluent, but my German is a bit shaky.
Translated and read the article - at this juncture, I would like you to lead this development and I will simply assist as and when required.
