### ISSUE TITLE
Simple List View - Column Width

### ISSUE THREAD

**Issue by depebo** [Egnarts94/JEM-Project#35]
Simple List in Modern Responsive on J!3.9.6 (Beez3)+ JEM 2.3.0-dev0.4 + demo data 
Need to find a better way to align: currently due to not specific width of last columns second, third and 4th columns can start at different positions.

![image](https://user-images.githubusercontent.com/14943618/57400383-3e5b9580-71cb-11e9-880f-7ca9659ded9c.png)

**Comment by Egnarts94** [comment]
It seems that you defined a column width for just some columns. Currently it works just with eighter no column width defined or all column widths defined with SumColumnWidth = 100% ConentWidth

**Comment by depebo** [comment]
That was from the default demo data install, no changes made. Suggest the settings for demo data install are amended.

**Comment by Egnarts94** [comment]
I think since JEM's default setting is the legacy layout, the default column widths are correct.
What do you think?

**Comment by depebo** [comment]
I hear you. Perhaps, we need to document these type of things, not sure what is the best place for this though.
Off topic: going forward (version 4 J!) we are probably going to ditch table layout anyway?

**Comment by Egnarts94** [comment]
> Off topic: going forward (version 4 J!) we are probably going to ditch table layout anyway?

If hoffi won't remove, it will stay as long as possible :(

**Comment by depebo** [comment]
defaults are set in Beta2 release
