### ISSUE TITLE
Module Wide - Overrun

### ISSUE THREAD

**Issue by depebo** [Egnarts94/JEM-Project#36]
Using Alternative Responsive (not sure if it is still a wip or can be tested) on J!3.9.6 (Beez3)+ JEM 2.3.0-dev0.4 + demo data. Might be good to have a note somewhere explaining difference between Modern and Alternative.
Issue: the content overruns module width.

![image](https://user-images.githubusercontent.com/14943618/57400927-80390b80-71cc-11e9-867f-45b4f5c4e701.png)

**Comment by jojo12** [comment]
Module wide is only for wide positions!

**Comment by Egnarts94** [comment]
The "Alternative" layout is developed by hoffi. I think its better when we not touch his overrides.

**Comment by jojo12** [comment]
In my eyes, alternative layout is a try to be as responsive as you can inside of the old known layout!

**Comment by jojo12** [comment]
@Egnarts94: I understand @depebo: That in the "help" should be mentioned the difference(s) between alternative_responsive, modern_responsive and default_table

**Comment by jojo12** [comment]
here's my JEM_wide on a wide position (banner):
![jemwide](https://user-images.githubusercontent.com/2960236/57430205-39c8c880-722f-11e9-8b1d-037238e084de.png)

**Comment by Egnarts94** [comment]
So, we should add an entry in the help that explain the different views?

**Comment by JKoelman** [comment]
that might be usefull,  

but would say that even as the module is meant for a wide position it can happen that people use it in a different position and in that case it might be user-friendly to don't let it overflow. Doesn't look nice. Think it would be better to crop it all up and messy between the borders... (if possible)

**Comment by Egnarts94** [comment]
The Responsive module will not overflow as far I know.
Depebo used the "Alternative Responsive" by hoffy. This override is not relevant an should be removed on a new release.

**Comment by depebo** [comment]
Proposed Actions

1. Remove option "Alternative Responsive" from available options in Layout Style (Settings / Basic Settings / Style)
2. Default Layout Style to "Modern Responsive"

@jojo12 @JKoelman @Egnarts94 Are we all in agreement?

**Comment by Egnarts94** [comment]
1. Yes I agree
2. That we should discuss. I am not shure, if it is good because all people updating JEM will be enforced to use the responsive layout. So there may be some angry guys... If we use the legacy layout as default, for people already using JEM it will change nothing.

**Comment by depebo** [comment]
will this work: set default to "Modern Responsive" in install sql, but not modify it in update sql. This way if you install from blank - you get responsive by default and if you upgrade - your current setting will stay put.
