### ISSUE TITLE
pkg_jem_v2.3.0-dev4.1: attachments remove doesn't work

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#41]
in editevent I uploaded an attachment, but I can't remove it (the button seams dead)
EDIT: The same is in editvenue

**Comment by Egnarts94** [comment]
It should been fixed within this commit: https://github.com/Egnarts94/JEM-Project/commit/823335a392deca05b7e0e38c91adb9ef2d6ab830
The latest build has it included, isn't it?

**Comment by jojo12** [comment]
I didn't install it yet, the map fix is just included too in this? dev.4.1?

**Comment by jojo12** [comment]
I tried with the attachments.js, on other places like image remove it works but not in attachments remove.

**Comment by jojo12** [comment]
installed pkg_jem_v2.3.0-dev4.1: but problem persists.

**Comment by depebo** [comment]
Can confirm remove attachment does not work as expected: (x) button is visible and as soon as you click on it (x) button disappears, but leaves the attachment row visible, making it confusing for the user. If you Save (or just Close!!!) then attachment is removed, as it was actually removed on (x) button press.

Solution: as soon as (x) button is pressed remove only that table row (not just (x) button). Ideally, function remove attachment should be called only if users is pressing Save (Save & Close).

before pressing (x)
![image](https://user-images.githubusercontent.com/14943618/57571106-8e23a200-7401-11e9-8174-9db16f6740da.png)
after pressing (x)
![image](https://user-images.githubusercontent.com/14943618/57571122-d17e1080-7401-11e9-9e2c-3856c1e66932.png)

Tested on the latest build from dev23-depebo branch in J! 3.9.6 on Chrome and IE

On a subject of attachments - if user doe not specify Access then attachment is not shown. Perhaps, default Access to Public?

**Comment by Egnarts94** [comment]
@jojo12 Did you clear the cache / reload the page new to cache (Shift+F5 or so)? Then it should work in dev4.1. I had to change the Javascript to get it working with the new icons and that is often cached by the browser.
@depebo The current process of removing an attachment needs to be changed. But I think that has no priority at the moment. Because it needs changes in all views, frontend and backend, and javascript. Let us fix the bug for the responsive part and the rest we do later.
What do you think about?

**Comment by depebo** [comment]
Definitively needs to be fixed, responsive part is a good start, please go ahead.

**Comment by jojo12** [comment]
@Egnarts94: Sorry, you need an answer. Even after cleaning the cache, the problem persists.

**Comment by Egnarts94** [comment]
That could also not be (technically). On my testpage it works properly.
Did you manually compare the files in the installation package with the files in your webspace? If you just install dev4.1 (or other since the better inclusion of jem-responsive) over my old responsive override, all old files were not removed.

**Comment by jojo12** [comment]
Sorry, I uninstalled the whole JEM with CleanupDB on uninstall=Yes.
I reinstalled pkg_jem_v2.3.0-dev.4.1 and tried again.
attachment remove works only on Backend, on Frontend there's the problem: you can't remove the attachment.
The special effect, @depebo describes, is on Backend. And I reproduced it there.

**Comment by Egnarts94** [comment]
Hey thank you jojo,
I also need to do a clean Joomla to find the bug. On some happy day I will have time... :D

**Comment by Egnarts94** [comment]
Sorry @jojo12 for my late response.
I installed a new Joomla with a clean JEM. Changed JEM to responsive layout and changed Settings->UserControl->AttachmentUploads to "Enable".
Then I can freely create and delete attachments of events in the frontend.
Tested with Firefox and Chrome - what Browser do you use?

**Comment by jojo12** [comment]
I use Firefox Developer, normally

**Comment by jojo12** [comment]
I am not sure, what version I am testing, I installed the version so called Beta 1, but then it says 2.3.0dev4 ?
I tested again, it's impossible to delete in frontend an attachment! In backend it works

**Comment by depebo** [comment]
Tested in both Chrome and Edge (Windows 10) and cannot re-create this issue.
![image](https://user-images.githubusercontent.com/14943618/63163537-96e9cc80-c01d-11e9-8c7c-9aa9313e8014.png)
First I get this view above and after pressing red cross get this (below)
![image](https://user-images.githubusercontent.com/14943618/63163570-aa953300-c01d-11e9-8950-6c75691170e3.png)
After pressing Save attachment does not exist.
Red cross does not change cursor to hand, but it still does the job. What error do you get @jojo12?

**Comment by jojo12** [comment]
Strange, but now I've seen: 
I was trying on Joomla 3.9.11 and JEM 2.3 Beta1 and Protostar-plus.  There it doesn't work.
I retried on Joomla 3.9.11 and JEM 2.3 Beta 1 and the normal Protostar. There it works. 
Shame on me, that I thought, protostar and protostar-plus are working the same way.
It's a pity: I liked protostar-plus so much!
Can be closed here on JEM. I am so sorry.
EDIT:
I tested on Beez3 too. There is no problem!

**Comment by depebo** [comment]
So, something on "-plus" version of template breaks it, let's keep that in mind for future. Perhaps, there is a case to switch to "-plus" template going forward?

**Comment by jojo12** [comment]
Sorry, I reopen this, because of the following:
Can it be that the problem has to do with the following:

In original Joomla (Protostar) template: 
all images with links or events show a hand when I mouseover,
only attachment remove (and image remove) show an arrow (never a hand) 
(Any way, it would be better if there would appear a hand! It helps the user. But for this I create a new item!)

(I have to say, that image remove works without problems even on protostar plus)

**Comment by jojo12** [comment]
Can it be that this is a "mootools conflicts with Bootstrap Joomla"?

**Comment by depebo** [comment]
Need to add <a> to make cursor change to hand.
