### ISSUE TITLE
Venue Description on Event Page is not Preparing Content

### ISSUE THREAD

**Issue by depebo** [Egnarts94/JEM-Project#44]
As per @jojo12 forum issue https://www.joomlaeventmanager.net/forum/jem-2-2-x-for-joomla-2-5-joomla-3-community-support/10492-problem-with-content-plugins-in-venue-description

**Comment by depebo** [comment]
@jojo12 @Egnarts94  please test and merge to your branch

**Comment by Egnarts94** [comment]
jojo has tested it.
Could you please add some comments what you do there? 
So that we know in 2 years what this part of code does...^^

**Comment by jojo12** [comment]
If you use e.g. xtd-plugins in venue description, the content prepare must prepare this not only in venue detail page but in event detail page too! With the addition of depebo this works.

**Comment by depebo** [comment]
@Egnarts94 did you want me to add comment to code or just here?
In code for event details view there is a block of statements that trigger various events, including content preparation. Code added was self explanatory, so I did not add the comment.
//use temporary class var to trigger content plugin for venue description

**Comment by Egnarts94** [comment]
Please to code :D
> //use temporary class var to trigger content plugin for venue description

Yea for example. Just to give a hint what this part of code does.
And I thought its not so self-explainable why we need a temporary class to do this.

**Comment by depebo** [comment]
@Egnarts94 Added comment and merged all your changes from develop-egnarts branch

**Comment by Egnarts94** [comment]
Yep, I merged it to my branch. When we solve the other bugs, I will update the dev23 branch.
