### ISSUE TITLE
error when "empty trash" JEM 2.3.0-dev2

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#47]
A lot of events are trashed. I choose them and click on "empty trash", I get the error:

Es ist ein Fehler aufgetreten!

    0 Using $this when not in object context

**Comment by Egnarts94** [comment]
I can not reproduce it.
What steps I need to do?

**Comment by jojo12** [comment]
Sorry, it's too late. Normally I use Firefox Developer.
I had to cleanup a site, So I trashed many events. Then I went to trash, choosed all events in the trash and clicked on "empty trash".  Then I got the error mentionned above.
Because I had to clean, I tried to destroy each event alone! this worked well. But because of that, I can't reproduce it anymore. When I meet this again, I will write.

**Comment by JKoelman** [comment]
**Installed**
JEM2.3.0.-dev.04.6


Did trash events, then emptied but can't confirm the notice.

**Comment by Egnarts94** [comment]
Frontend or backend?

**Comment by depebo** [comment]
Cannot recreate in the latest release. @jojo12 can you confirm you still have this issue using the latest release?

**Comment by jojo12** [comment]
I don't know, because since then, I had not to delete so many events. 
Can be closed. I will have to reopen when I encounter this again
