### ISSUE TITLE
Backend publish (unpublish) from list - modified date doesn't change

### ISSUE THREAD

**Issue by depebo** [Egnarts94/JEM-Project#49]
When admins or users edit Event or Venue form (backend or frontend), the modified date changes as well. But when in backend admins publish (or unpublish) an item from list (Events or Venues) by its Status link, than the modified date doesn't change.
See details in this thread, Issue and solution by [iberan](
https://www.joomlaeventmanager.net/forum/profile/6249-iberan)
[JEM Forum Post 26309](https://www.joomlaeventmanager.net/forum/jem-2-2-x-for-joomla-2-5-joomla-3-community-support/10655-backend-publish-unpublish-from-list-modified-date-doesn-t-change#26309)

**Comment by Egnarts94** [comment]
@depebo Can you fix it?
As far I see, in the forum topic there may be a solution?
