### ISSUE TITLE
fontawesome map-marker-plus would be better

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#5]
there's this icon, but only in fontawesome 5.4 free
is it possible to go there?

**Comment by Egnarts94** [comment]
If you mean for adding new venue? Yes, the problem is, that I do not understand the packages of FontAwesome5 and also their license, thats why I used FontAwesome4^^

**Comment by jojo12** [comment]
Mee too, but I will look for explanation. For the monent it is ok

**Comment by Egnarts94** [comment]
The map-marker-plus is in the premium package, so we have to pay for that. And I think we shouldn't do that.

**Comment by jojo12** [comment]
I agree
