### ISSUE TITLE
2.2.3-dev046 | Site-MyeventsView, tmpl-response | link to manage attendees trows an error

### ISSUE THREAD

**Issue by JKoelman** [Egnarts94/JEM-Project#50]
When clicked at the link to show the attendees it trows an error.
The addremove button is not defined.

` Call to undefined method JemOutput::addremovebutton() `

**Comment by Egnarts94** [comment]
This ist already fixed see https://github.com/Egnarts94/JEM-Project/commit/0e1b8e4d2f97bc8d761ec402717ea190943d211c
But thx for the hint.

**Comment by depebo** [comment]
@JKoelman can this be closed?

**Comment by JKoelman** [comment]
ah yeah didn't take a peak at the recent commits so that woud be ok.
