### ISSUE TITLE
Deprecated (at least in Joomla 3.9 and php 7.2

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#6]
in JEM 2.3dev1:Deprecated: Function create_function() is deprecated in mysite.ch/subdomains/intra/httpdocs/components/com_jem/classes/user.class.php on line 229

**Comment by Egnarts94** [comment]
Affected files:
site/classes/user.class.php line 229
site/models/eventslist.php line 419, 423

**Comment by jojo12** [comment]
On php 7.2 this is important for the old JEM 2.2.3 too! And has to be fixed!

**Comment by Egnarts94** [comment]
It's fixed for JEM-Responsive and default JEM... What do you mean?

**Comment by jojo12** [comment]
Yes, but it depends, when we will officially bring JEM 2.3. All those who use JEM 2.2.3 and php 7.2 will get Notifications. I think this will force us to bring JEM 2.3 earlier or to give a patch to adapt the concerned files!
