### ISSUE TITLE
beta2: Eventdescription and Venuedescription have lost JCE

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#60]
Testing JEM2.3.0 beta2 local on clean Joomla 3.9.11 Protostar

**Comment by jojo12** [comment]
Really strange: After about 10 times looking into event edit and venue edit, suddenly JCE is there. 
I don't know what I changed.
(So because of this, I don't close this issue)

**Comment by depebo** [comment]
@jojo12 Can you confirm you have the same behavior if using default editor TinyMCE please?

**Comment by depebo** [comment]
This is Venue edit page front end with default editor TinyMCE
![image](https://user-images.githubusercontent.com/14943618/63441700-bde33c80-c429-11e9-87d7-25e12e900ce7.png)

And this is Venue edit front end using JCE editor, note increased requests and load time
![image](https://user-images.githubusercontent.com/14943618/63441794-e0755580-c429-11e9-9d22-2d38f897b0c0.png)

Both tests using Chrome 76 on local site J!3.9.11 running from Joomlatools Vagrant.

**Comment by depebo** [comment]
@jojo12 please confirm this is still an issue

**Comment by jojo12** [comment]
no, but I don't know why was this. Can be closed
