### ISSUE TITLE
Testing JEM 2.3.0beta2: JCE xtd-buttons

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#62]
In event edit, there are 6 xtd-buttons (module, menu, contact, article, image,readmore),
In venue edit there are only 4 xtd-buttons (image and readmore are hidden)
why?

**Comment by depebo** [comment]
There is a difference in event edit and venue edit editor display:
Event has 
`hide="pagebreak"`
Venue has 
 `hide="pagebreak,readmore,image"`
This has not been changed for a while.
Now, I am not sure why there needs to be a difference in editing description of Event vs Venue, so I am for making it uniform, like Event edit.
Objections?
