### ISSUE TITLE
FR: Changing order in editvenue form

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#63]
I add my way for responsive edit venue form:
[edit_venue_responsive.zip](https://github.com/Egnarts94/JEM-Project/files/3525121/edit_venue_responsive.zip)

I want it similar the edit event form. 
But Image is much less basic than for events: So image and URL are in extended tab.
Do you agree?
I adapted from beta 2

**Comment by depebo** [comment]
Sounds good, thank you. I shall check and merge to the next release.

**Comment by depebo** [comment]
turn remove image/attachment into buttons, display google map if selected in settings, add missing text constants, split save/cancel to be the same as event edit
