### ISSUE TITLE
Testing JEM2.3.0beta2: resp my events breaked template (hint for columns is important!)

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#67]
my settings for views are good on other sides, but here:
![brokentempmyevents](https://user-images.githubusercontent.com/2960236/63491513-a81c5880-c4b7-11e9-9810-819e30450e84.png)

the same for myattendances

**Comment by depebo** [comment]
site\views\myevents\tmpl\responsive\default_events.php
has 2 issues
1. it was not respecting attending setting and was always showing attending
2. in addition to columns selected in settings it was showing select tick and status, thus pushing table width past 100%
Temporary fix: take 5% from date and title columns to allow for non conditional columns display

**Comment by depebo** [comment]
Same with my Attendance view, with addition of longer comment field. Need at least 13% to show status and comment fields. It is a temporary hack though.
