### ISSUE TITLE
helpful in FE for admins and group members

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#73]
The persons who are allowed to create/edit events can come easier to attending manager
(they can come to the same by using "myevents")
if you add in site/event/views/view.html.php
in about line 202

`		// Check if user can edit attendees
		//$isAuthor = $userId && ($userId == $item->created_by);
		//$permissions->canEditAttendees = $isAuthor;
		// Check if user can edit events (admins and group members)
		$permissions->canEditAttendees = $user->can('edit', 'event', $item->id, $item->created_by);

`

**Comment by depebo** [comment]
cannot comment out 
`//$isAuthor = $userId && ($userId == $item->created_by);`
cause it is used on line 223 as a part of test
`$this->showAttendees = (($g_reg == 1) || (($g_reg == 2) && ($e_reg & 1))) && ((!(($e_reg & 2) && ($g_inv > 0))) || (is_object($registration) || $isAuthor));`
Updated `$permissions->canEditAttendees`

**Comment by jojo12** [comment]
it doesn't work like that:
When the setting is:  all registered can create events, then registered user is not possible.
but he should, because he is author too!
(but better than nothing)
