### ISSUE TITLE
added new words/key after all in edit event and edit venue (to be more clear)

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#75]
with the new order of edit event and edit venue, there are arrived new words/keys.
How they come into the basic transifex language files? Automacticly?

**Comment by depebo** [comment]
Reply from Ernst: 
Yes, transifex files are updated every night directly from GitHub

**Comment by depebo** [comment]
More specifically branch dev21 (or dev23) from jemproject/JEM-Project
So, nothing will be in transefix yet from this repo
