### ISSUE TITLE
JEM_2.3.0_beta2

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#76]
I used the JEDchecker and compared JEM 2.2.3 with JEM 2.3.0 Beta 2:

Good is: all JErrors are now away! 

Some warnings are the same (surely because of compatibility to Joomla 2.5) , this seems to be ok, but must be controlled by JED

New warnings are but new are:

> 3 Compatibility Issues - Click to View Details
    • #001 C:\xampp\htdocs\joomla_30\tmp\jed_checker\unzipped\pkg_jem_v2.3.0-beta2(1).zip/packages/com_jem/admin/controllers/attendee.php in line: 53
    JRequest is deprecated, you should use JFactory::getApplication()->input;:
    • $attendee->bind(JRequest::get('post')); // before Joomla! 3.2.0 there is no good way to get them all from JInput :(
    • #002 C:\xampp\htdocs\joomla_30\tmp\jed_checker\unzipped\pkg_jem_v2.3.0-beta2(1).zip/packages/com_jem/admin/controllers/attendee.php in line: 81
    JRequest is deprecated, you should use JFactory::getApplication()->input;:
    • $post = JRequest::get('post'); // before Joomla! 3.2.0 we must and can use JRequest
    • #003 C:\xampp\htdocs\joomla_30\tmp\jed_checker\unzipped\pkg_jem_v2.3.0-beta2(1).zip/packages/mod_jem_teaser/tmpl/responsive/default.php in line: 18
    JRequest is deprecated, you should use JFactory::getApplication()->input;:
    • if (JRequest::getVar('jem-rss','0') == 1) {

**Comment by jojo12** [comment]
It seems that newly column of attendees in myevents is together with simplelist column of attendees. 
But this is (in my eyes) not so good! 
If an eventcreator decides not to show the number of attendees for public, he wants perhaps to see the number of attendees in myevents.

**Comment by jojo12** [comment]
in JEM_2.3.0_Beta 3.1 it shows:
JEM_2.3.0_Beta3.1

10 Errors - Click to View Details
•	#001: C:\xampp\htdocs\joomla_30\tmp\jed_checker\unzipped\pkg_jem_v2.3.0-beta3.1.zip/packages/com_jem/admin/controllers/source.php
You've used encoding in this file. This is not an error, but a JED editor will have to review this file.
•	#002: C:\xampp\htdocs\joomla_30\tmp\jed_checker\unzipped\pkg_jem_v2.3.0-beta3.1.zip/packages/com_jem/admin/models/cssmanager.php
You've used encoding in this file. This is not an error, but a JED editor will have to review this file.
•	#003: C:\xampp\htdocs\joomla_30\tmp\jed_checker\unzipped\pkg_jem_v2.3.0-beta3.1.zip/packages/com_jem/admin/models/source.php
You've used encoding in this file. This is not an error, but a JED editor will have to review this file.
•	#004: C:\xampp\htdocs\joomla_30\tmp\jed_checker\unzipped\pkg_jem_v2.3.0-beta3.1.zip/packages/com_jem/site/classes/output.class.php
You've used encoding in this file. This is not an error, but a JED editor will have to review this file.
•	#005: C:\xampp\htdocs\joomla_30\tmp\jed_checker\unzipped\pkg_jem_v2.3.0-beta3.1.zip/packages/com_jem/site/controllers/event.php
You've used encoding in this file. This is not an error, but a JED editor will have to review this file.
•	#006: C:\xampp\htdocs\joomla_30\tmp\jed_checker\unzipped\pkg_jem_v2.3.0-beta3.1.zip/packages/com_jem/site/controllers/venue.php
You've used encoding in this file. This is not an error, but a JED editor will have to review this file.
•	#007: C:\xampp\htdocs\joomla_30\tmp\jed_checker\unzipped\pkg_jem_v2.3.0-beta3.1.zip/packages/com_jem/site/models/editevent.php
You've used encoding in this file. This is not an error, but a JED editor will have to review this file.
•	#008: C:\xampp\htdocs\joomla_30\tmp\jed_checker\unzipped\pkg_jem_v2.3.0-beta3.1.zip/packages/com_jem/site/models/editvenue.php
You've used encoding in this file. This is not an error, but a JED editor will have to review this file.
•	#009: C:\xampp\htdocs\joomla_30\tmp\jed_checker\unzipped\pkg_jem_v2.3.0-beta3.1.zip/packages/com_jem/site/views/attendees/view.html.php
You've used encoding in this file. This is not an error, but a JED editor will have to review this file.
•	#010: C:\xampp\htdocs\joomla_30\tmp\jed_checker\unzipped\pkg_jem_v2.3.0-beta3.1.zip/packages/plg_jem_mailer/mailer.php
You've used encoding in this file. This is not an error, but a JED editor will have to review this file.

**Comment by depebo** [comment]
The first past JRequest is related to conditional code run for version J!<3.2 - I'll remove that code later today
The second - about attendees - should be a separate issue
The third - 10 errors - is a warning that base64 encode/decode has been used. We have 10 files in JEM:
![image](https://user-images.githubusercontent.com/14943618/64677548-b1259780-d46f-11e9-811d-0ff9f9db74c9.png)
Has not been changed for a while and I am not sure it should at this point.

**Comment by jojo12** [comment]
The compatibility issues have always a comment: it seams this helps the JEDcheckers to understand why this old code is there (I think this is because of the compatibility with Joomla! 2.5.
