### ISSUE TITLE
Urgent! JEM 2.2.3+ Backend Problem creating new venue!

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#82]
I can reproduce this issue (from 2 others) in forefox in Backend on a clean joomla 3.9.14 on php 7.3.11 with protostar template and JEM 2.2.3. On JEM 2.3.0 prerelease too!
I don't know since when this comes. (Because the use of creating new venues is not so needed, it is possible, that it is not yet found earlier.)
In backend I create a new venue, I insert a name, then I go to image and choose an image on my harddisk. Then I click "upload", I get the notification, that the upload is ok. But immediately the editvenue window closes and there's no new venue saved.
(meanwhile the solution is: Before choosing and uploading an image, you first have to save the new venue, after you can upload an image!)
**BUT: THIS ist not a solution! URGENT!**
EDIT: the same problem, when you want to create a new event with an image!

**Comment by depebo** [comment]
@jojo12 I cannot re-create the issue in Chrome or Edge on J! 3.9.15-rc + JEM 2.3.0-beta3.2 in either front and back end.
Can you confirm it happens in Chrome / Edge on your machine?

**Comment by jojo12** [comment]
@depebo: I tried with chrome: there's no such problem. in events, categories and venues.
Only in firefox!
Will test in other browsers.
EDIT: 
In Edge it works fine.

**Comment by jojo12** [comment]
![Webkonsole_image](https://user-images.githubusercontent.com/2960236/73427707-b3619300-4337-11ea-80d3-308257129c69.png)
I don't know, if you just did find a solution.
With Webconsole in firefox developer I found the following: (see image).
there seems to be a deprecated thing (in joomla 3 too)
Is it possible, it has to do with jquery and an old jquery-migrate?
But I found too, that they planned to update jquery-migrate for joomla 4. 
But joomla 4 is too late.
Is it possible that JEM uses joomlas jquery which is deprecated? And only firefox is strict with deprecated? #
[Infos SyntaxError_image.pdf](https://github.com/Egnarts94/JEM-Project/files/4132649/Infos.SyntaxError_image.pdf)

**Comment by depebo** [comment]
only happens on 64 bit version of Firefox

**Comment by jojo12** [comment]
should firefox know this difference?

**Comment by depebo** [comment]
Removed `window.history.go(-1);` from command from lines 86/89 in admin\controllers\imagehandler.php
Testing...
