### ISSUE TITLE
Bug: in Frontend when editing an event, the category is lost

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#87]
I wanted to edit an event in Frontend. I change something and want to save, saving is not accepted because there's no chosen category. 
This means the earlier category is lost with opening the event!

(JEM 2.3.0 Beta 3 on Joomla 3.9.15 php 7.3.13

**Comment by depebo** [comment]
Cannot reproduce this issue in Chrome of Firefox. Frontend event edit by pressing anchor at this path:
/html/body/div[1]/div/div/main/div[2]/h1/a[1]

**Comment by jojo12** [comment]
I tested again: strange! I don't encounter this anymore. Will continue to test and announce if I will encounter again. Sorry!

**Comment by jojo12** [comment]
I think this can be closed
