### ISSUE TITLE
JEM 2.3dev1: myevents and myattendings not yet finished

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#9]
allways testing in responsive part:
the layout in not yet good!

**Comment by Egnarts94** [comment]
What is not ready yet in those views?
Its the small table like in all other views and not the modern list because of the Select-Checkbox and the Status-Icon.

**Comment by jojo12** [comment]
I test actually after all with the responsive: see image
![myev](https://user-images.githubusercontent.com/2960236/47344081-e5e9fe00-d6a7-11e8-86d1-bf837290da66.png)

myattendings is about the same

I use them in a 3 column site on a desktop /in a 2 column site too

**Comment by Egnarts94** [comment]
This happens because you have set some "Column Width" values in Backend->JEM->Settings->Layout

**Comment by jojo12** [comment]
your're right! How did you know :-)
